apiVersion: v2
name: openauth
description: OIDC issuer wrapping @fredericrous/openauth (Hono + Postgres storage + SMTP).
type: application
version: 0.0.5
appVersion: 0.0.5
maintainers:
  - name: frederic.rous
icon: https://github.githubassets.com/images/icons/emoji/lock_with_ink_pen.png
